### ISSUE TITLE
Consider adding an ABI call to get unique id for each VM

### ISSUE THREAD

**Issue by bianpengyuan** [proxy-wasm/proxy-wasm-cpp-host#135]
This will allow extension to selectively enable logic at some VMs. For example, for a local rate limit extension, we'd only want one VM to do token bucket refilling, and VM uid enable such a use case by register the uid at shared data.

**Comment by mathetake** [comment]
Sounds reasonable, but I believe this could be achieved through get_property calls in Envoy (through foreign function interface).

**Comment by mathetake** [comment]
The point is that: whether or we should have a dedicated function call for VM unique ID.

**Comment by PiotrSikora** [comment]
> This will allow extension to selectively enable logic at some VMs. For example, for a local rate limit extension, we'd only want one VM to do token bucket refilling, and VM uid enable such a use case by register the uid at shared data.

Could you elaborate more on this use case? Do you want `plugin_foo` running in `vm_id: a` to do refills, but the same `plugin_foo` running in `vm_id: b` to not perform them? Why not use plugin configuration to enable it in one, but not the other?

**Comment by bianpengyuan** [comment]
> Could you elaborate more on this use case? Do you want plugin_foo running in vm_id: a to do refills, but the same plugin_foo running in vm_id: b to not perform them? Why not use plugin configuration to enable it in one, but not the other?

I want `vm: a` at worker_0 to refill token bucket, but not `vm: a` at other worker threads.

**Comment by PiotrSikora** [comment]
> I want `vm: a` at worker_0 to refill token bucket, but not `vm: a` at other worker threads.

The `vm_id` is the same across worker threads, so you need a way to differentiate worker threads.

I think that a bit cleaner design would be if the refilling task was a separate background task (singleton), and not something intermixed with request processing. What do you think?

**Comment by bianpengyuan** [comment]
> I think that a bit cleaner design would be if the refilling task was a separate background task (singleton), and not something intermixed with request processing. What do you think?

Yeah I agree, but even for that singleton VM, if we want to use the same module as worker thread VMs for convenience, we'd still need to have a way to distinguish if this is a singleton instance. So I think this will still be valuable, or is there already another way?

**Comment by PiotrSikora** [comment]
> Yeah I agree, but even for that singleton VM, if we want to use the same module as worker thread VMs for convenience, we'd still need to have a way to distinguish if this is a singleton instance. So I think this FR will still be valuable, or is there already way?

Singleton could have different plugin configuration (available right now) and/or different context type (future ABI).

While exposing `worker_thread_id` should be possible via `get_property`, assigning work to a single worker is going to be a bit tricky, since they are all equal (e.g. `id=213`, `id=214`, `id=215` or totally random on systems with randomizd PIDs and/or on different proxies). You could store `worker_thread_id` in KV and execute task only on the matching ID, but that's a bit hacky.

I'd also prefer to avoid creating such anti-patterns (doing singleton work in request path) in examples, to be honest.

**Comment by bianpengyuan** [comment]
> Singleton could have different plugin configuration (available right now) and/or different context type (future ABI).

Yeah realized that they can simply have different configs. Probably this is not a good example for necessity of this new ABI. Part of reason is just that Istio does not have a friendly way to customize bootstrap. I think this will be useful for other reasons, such as debugging, but we can close this for now and revisit if other use cases come up. Thanks!
