### ISSUE TITLE
Resolve symbol collisions among Wasm runtimes

### ISSUE THREAD

**Issue by mathetake** [proxy-wasm/proxy-wasm-cpp-host#139]
Migrated from https://github.com/envoyproxy/envoy/issues/14012. 

The more runtime we have, The more we want to have single binary to, at least, benchmark all at once. 

Using `objcopy --prefix-symbols` on all the object files of runtimes might be a solution, though I'm not sure what changes would be necessary to be applied to C++ interfaces (V8 and WAVM for examples). Changes to the C interfaces would be trivial.
And This might have side effects in the final binary size?

Relevant to #113

**Comment by PiotrSikora** [comment]
I'm all in for fixing this issue, but do we have any real use case for it, other than benchmarks?

**Comment by mathetake** [comment]
No, I don't have any specific real use case. So this is going to be my weekend task when I have time until the real necessity comes up.

**Comment by mathetake** [comment]
I found that `--prefix-symbols` cannot be used for this purpose since it literally prefixes every symbol and we end up having something like `my_prefix_pthread_mutex_unlock` which is a mess. Instead, we can use `redefine-sym` for renaming every duplicated symbol and leaving others intact. I have a prototype in my local machine.
