### ISSUE TITLE
Extract common code from runtime implementations

### ISSUE THREAD

**Issue by PiotrSikora** [proxy-wasm/proxy-wasm-cpp-host#148]
Unfortunately, we have a lot of code duplication and runtime-agnostic code in runtime-specific implementations. At the very least, all bytecode parsing (`getCustomSection`, `getStrippedSource`, `buildFunctionNameIndex`), logic around precompiled modules and signature verification should be extracted to common utils.

**Comment by PiotrSikora** [comment]
@mathetake any interest in taking this? :)

**Comment by mathetake** [comment]
yeah, let me take this:)
