### ISSUE TITLE
Add WasmEdge Runtime

### ISSUE THREAD

**Issue by daixiang0** [proxy-wasm/proxy-wasm-cpp-host#172]
Details refer to https://github.com/WasmEdge/WasmEdge

Not sure need request a feature in envoy ...

/cc @PiotrSikora

**Comment by mathetake** [comment]
Thanks, I didn't know that SSVM is renamed to WasmEdge. Duplicated with https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/97 so closing this.
