### ISSUE TITLE
What is the difference between proxy-wasm-cpp-host and proxy-wasm-cpp-sdk

### ISSUE THREAD

**Issue by coolg92003** [proxy-wasm/proxy-wasm-cpp-host#315]
Hi Expert,
What is the difference between proxy-wasm-cpp-host and proxy-wasm-cpp-sdk?

The Major reason that I ask this is that the proxy-wasm-cpp-sdk is seldom updated now.
does this meaning that the latest wasm developing which will move to  proxy-wasm-cpp-host?

thanks and regards!
Cliff

**Comment by lum1n0us** [comment]
*proxy-wasm-cpp-sdk* is for Wasm application
*proxy-wasm-cpp-host* is for Cpp application(Host)

**Comment by coolg92003** [comment]
Hi Lum1n0us,
thanks!!!
Cliff

**Comment by mpwarres** [comment]
Closing this issue since @lum1n0us answered the question above (thanks!)
If further info is needed, please feel free to reopen.
