### ISSUE TITLE
[CI] `cargo-raze` is uninstallable abandonware, adopt crate_universe

### ISSUE THREAD

**Issue by phlax** [proxy-wasm/proxy-wasm-cpp-host#388]
The `cargo-raze` repo states:

> **cargo-raze is currently an unmaintained and unsupported product.**

> [crate_universe in rules_rust](https://bazelbuild.github.io/rules_rust/crate_universe.html) is a supported and maintained product with similar aims.

not sure how to update to use `rules_rust` for this but this is one of the causes of #386 

error is

```console
 Caused by:
  failed to select a version for the requirement `cargo_toml = "^0.8.1"`
  candidate versions found which didn't match: 0.19.2, 0.19.1, 0.19.0, ...
  location searched: crates.io index
  required by package `cargo-raze v0.14.1`
  if you are looking for the prerelease package it needs to be specified explicitly
      cargo_toml = { version = "0.19.0-beta.1" }
  perhaps a crate was updated and forgotten to be re-vendored?
```

**Comment by phlax** [comment]
fwiw i tried with various rust versions using:

```console
docker run --rm -it rust  cargo install cargo-raze
```
to similar effect

**Comment by martijneken** [comment]
+1 crate_universe is the way
